name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          #gcc -ftest-coverage -fprofile-arcs -O0 -o test test.c lib.c
          clang -fprofile-instr-generate -fcoverage-mapping  lib.c test.c -o test
          ./test
          #gcov -abcfu lib.c
          llvm-profdata merge -sparse default.profraw -o default.profdata
          #llvm-cov show ./test -instr-profile=default.profdata
          #llvm-cov report ./test -instr-profile=default.profdata
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
           #files: ./lib.c.gcov
           files: ./default.profdata
